### ISSUE TITLE
Cozydb 0.18 error deletion

### ISSUE THREAD

**Issue by Peltoche** [Peltoche/cozy-sound#21]
The PUT command work, and in the previous cozydb version my function work so... WTF?!

```
Error: Server error occured.
  at /Volumes/Data/nfs/zfs-student-5/users/2014_paris/ppeltier/vms/cozy1/new/node_modules/cozydb/lib/cozymodel.js:123:27
  at parseBody (/Volumes/Data/nfs/zfs-student-5/users/2014_paris/ppeltier/vms/cozy1/new/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
  at IncomingMessage.<anonymous> (/Volumes/Data/nfs/zfs-student-5/users/2014_paris/ppeltier/vms/cozy1/new/node_modules/cozydb/node_modules/request-json-light/main.js:105:14)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)
```

**Comment by Peltoche** [comment]
Temporary fix with cozydb V0.0.16
